### ISSUE TITLE
Missing cursor on Daydream View

### ISSUE THREAD

**Issue by nsteins** [googlecreativelab/inside-music#1]
I can get the site to load in VR through the daydream, but I don't see any cursor/retical or a means to interact in order to select a song. I am able to use the controller to recenter the view right before loading, so I don't believe it's a connectivity issue.

Looking at [controls.js](https://github.com/googlecreativelab/inside-music/blob/master/src/controller/controls.js), there appears to be a typo in the components definition under the value associated with the types.DAYDREAM key, which I suspect should be 'custom-gearvr-controller'. 

Anyway if more info helps: I am on Android 7.1.2, Chrome 61.0 and using a pixel xl.

**Comment by hapticdata** [comment]
good catch on the typo! However this might not be the issue. Have you pressed a button on the controller after entering the experience? Unfortunately the controller does not appear connected via the Gamepad API until after a button has been pressed after entering the experience.

Please try entering the experience and then pressing a button on the controller and let me know whether or not the controller it appears. It should, but either way perhaps we need a dialog etc.

thanks!

**Comment by nsteins** [comment]
I was just able to test it again and like I remembered, the controller does not appear after clicking the track pad button. Clicking the middle app button dumps me to a different view with a 2d rendering of the experience front page, and clicking the home button takes me to the daydream app.

I forgot to mention in my first post: I could not initially get the experience to work with the daydream. When I would click the vr view, it would immediately show the split screen video (clicking on the settings button gave me the option of selecting Cardboard 2014 or 2015, but not Daydream).

I was only able to get the experience to load in the daydream view by enabling chrome://flags/#enable-webvr. I'm not sure if this makes a difference.

**Comment by nsteins** [comment]
I found the solution! I had to change the flag at chrome://flags/#enable-gamepad-extensions from 'Default' to 'Enabled'.  As soon as I did that, the controller loaded properly.

I'm not sure if you want to put that information on the experience site (or if you have a different browser recommended for webvr experiences), but I'm gonna close this issue.

**Comment by ghost** [comment]
Hey guys! So I'm having the same issue listed as above only on a Pixel XL running 8.1. I've tried all combinations of enabling webvr & the gamepad-extension flags and still can't seem to get a cursor. I've reset the flags and restarted the phone but still can't seem to get a cursor in Daydream. Any other thoughts on flags I might need to change from "default" to "enabled"?
