### ISSUE TITLE
Experience stops at loading (audio do not start)

### ISSUE THREAD

**Issue by SauloCarranza** [googlecreativelab/inside-music#8]
Hi, first time writing on github (so sorry for the errors).

After following all the steps, I got to the part of launching the index file on al local server. Unfortunately, once I select the song that I want to play, it gets stucked al the "loading" screen (I can rotate with the mouse or oculus, but the audio never start).

I've tried on OSX (Yosemite)  and Windows 10. Firefox, Chrome and Chromium and the result is the same, so I do not have more clues honestly.

Hope some of you guys can help me.

Thanks by advance!

**Comment by ryburke** [comment]
Hi Saulo, thanks for your question. Unfortunately, the stems are not part of the open source repo, only the code. You'll need to link your own music stems in the project.
